### PR TITLE
(maint) Bump Leatherman and use `leatherman_install`

### PR DESCRIPTION
**Pull request by MikaelSmith**
Bump Leatherman to get the `leatherman_install` utility, and use it to
simplify install logic.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Requires https://github.com/puppetlabs/leatherman/pull/115 for the Windows error.

**Comment by kylog** [comment]
So bump the lth sha now?

**Comment by MikaelSmith** [comment]
Updated again.

**Comment by MikaelSmith** [comment]
Passed.

**Pull request merged**
