### PR TITLE
(maint) Resolves #12: add doxygen generation and verification

### LINKED ISSUE #12: Add doxygen generation and verification
The template should generate documents using doxygen from the library, and use a Travis job to ensure that doesn't produce any warnings.

### PR DESCRIPTION
**Pull request by MikaelSmith**
Adds doxygen generation from template configuration files, and adds
verification to the Travis CI job.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
@peterhuene, when you have a chance can you give this a review?

**Comment by MikaelSmith** [comment]
@kylog this uses an example of generating the Doxygen configs so we only specify version in one place.

**Comment by MikaelSmith** [comment]
This is meant to be an example of using Doxygen in our projects. On that note, maybe I should add an internal section, and not use Doxygen for that part of it as suggested by @branan.

**Comment by MikaelSmith** [comment]
ping for review

**Comment by kylog** [comment]
LGTM. 

What does "maybe I should add an internal section, and not use Doxygen for that part of it" mean? I didn't follow that comment.

**Comment by MikaelSmith** [comment]
Internal headers. We have a pattern of having internal header files that we don't ship; @branan raised the question somewhere of whether it's worth having the full Doxygen documentation for that.

**Comment by kylog** [comment]
Ah gotcha. That's a reasonable idea for a refinement, but doesn't merit holding off on this IMHO.

**Pull request merged**
